In [1]:
%reload_ext autoreload
%autoreload 2

In [64]:
from utils import poses

In [154]:
def clip_the_point_max_step(worst_frog_pos, best_frog_pos):
    t = 10/np.linalg.norm(worst_frog_pos - best_frog_pos)
    new_change = (1 - t)*worst_frog_pos + t*best_frog_pos
    return new_change

In [164]:
sfla_1.memeplexes = sfla_1.sort_frog()

In [191]:
new_q, new_t = sfla_1.new_step(sfla_1.structinfo[5][1], sfla_1.structinfo[5][2], sfla_1.structinfo[9][1], sfla_1.structinfo[9][2])

In [192]:
new_q_1, new_t_1 = sfla_1.new_step_test(sfla_1.structinfo[5][1], sfla_1.structinfo[5][2], sfla_1.structinfo[9][1], sfla_1.structinfo[9][2])

In [195]:
final = sfla_1.ligand.tranformation(new_q_1, new_t_1)   #final = np.array([Uq.rotate(i) for i in self.lig_atom])  
results =sfla_1.find_score([final, 101, new_q_1, new_t_1])

MSMS running for poses/out101.pdb
MSMS finished with poses/out101.pdb


In [199]:
np.linalg.norm(new_t_1)

21.182364076911945

In [196]:
results

(46381.94082487143,
 101,
 Quaternion(0.7908955136993902, 0.02198214455782066, -0.22075132550856919, 0.5703244024386703),
 array([ -2.64304872, -20.13472692,   6.02491602]))

In [189]:
sfla_1.structinfo[5]

[-30.397091764806422,
 Quaternion(0.8105213235790795, 0.03500468907997499, -0.07755693990824637, 0.5794952776667813),
 array([ -9.98857793, -18.98548946,  28.15920725])]

In [190]:
sfla_1.structinfo[9]

[48076131.94406144,
 Quaternion(0.5161136363828437, -0.037365014798154295, -0.7602118175000121, 0.3928212857549089),
 array([  0.50284043, -20.62691388,  -3.45459522])]

In [180]:
new_t_1

array([-5.55242414, -1.75247124, 30.52201395])

In [173]:
sfla_1.step_size = 10

In [169]:
sfla_1.structinfo[22]

Quaternion(0.8773262983303337, -0.44705412890200386, 0.05120826949124852, -0.16678994341799044)

In [165]:
sfla_1.memeplexes

array([[39.,  8., 47., 13., 22.],
       [ 5., 11., 44., 42.,  9.],
       [41., 15., 20., 46., 32.],
       [26., 17.,  3.,  1., 19.],
       [ 7., 24., 36., 34., 14.],
       [16., 27., 35., 43.,  0.],
       [18., 28., 38., 37., 48.],
       [33., 31., 10.,  4., 25.],
       [ 6., 40., 21., 49., 23.],
       [29., 45., 12.,  2., 30.]])

In [1]:
%reload_ext autoreload
%autoreload 2

In [1]:
from sfla import SFLA 

In [2]:
model = SFLA(frogs=50, mplx_no=10, no_of_iteration=2, no_of_mutation=2, q=4)

In [3]:
model.run_sfla_test("Data/4dn4_LH:M/", "4dn4", "LH", "M")

2021-06-28 11:06:49,712 [sfla: INFO] Starting SFLA algorithm
2021-06-28 11:06:52,829 [sfla: INFO] Generating initial population (Number of frogs: 50)
2021-06-28 11:07:02,887 [sfla: INFO] out39.pdb -- score = 0.000
2021-06-28 11:07:13,382 [sfla: INFO] out4.pdb -- score = 0.000
2021-06-28 11:07:13,410 [sfla: INFO] out1.pdb -- score = 0.000
2021-06-28 11:07:14,650 [sfla: INFO] out2.pdb -- score = 0.000
2021-06-28 11:07:14,997 [sfla: INFO] out6.pdb -- score = 0.000
2021-06-28 11:07:16,389 [sfla: INFO] out5.pdb -- score = 19704289.106
2021-06-28 11:07:16,803 [sfla: INFO] out10.pdb -- score = 3924011.986
2021-06-28 11:07:17,004 [sfla: INFO] out36.pdb -- score = 0.000
2021-06-28 11:07:17,256 [sfla: INFO] out25.pdb -- score = 31618718.291
2021-06-28 11:07:17,791 [sfla: INFO] out0.pdb -- score = 1001851.241
2021-06-28 11:07:17,892 [sfla: INFO] out20.pdb -- score = 5801502.661
2021-06-28 11:07:17,915 [sfla: INFO] out21.pdb -- score = 25265.738
2021-06-28 11:07:18,838 [sfla: INFO] out7.pdb -- sco

In [4]:
model.memeplexes

array([[15.,  3., 44., 48.,  5.],
       [29., 22.,  9.,  0., 25.],
       [12.,  1., 24., 46., 37.],
       [13.,  2., 26., 32., 17.],
       [47.,  4., 19., 23., 38.],
       [34.,  6., 21., 35., 11.],
       [28., 27., 45., 18., 42.],
       [14., 36.,  7., 10.,  8.],
       [40., 39., 43., 20., 33.],
       [30., 31., 41., 16., 49.]])

In [5]:
model.conformation_data[15]

[-76.18173825324475,
 Quaternion(0.7566750526037491, 0.20182174219601048, -0.6086322311546324, 0.12758391882919481),
 array([-31.44959975, -22.07516527,  17.31679871])]

In [6]:
model.conformation_data[29]

[-24.39316901117409,
 Quaternion(0.48637570542402786, 0.804120104886761, 0.32360681410431974, 0.11003708445535995),
 array([-18.41405475,   3.98984686,  46.4517414 ])]

In [7]:
model.run_remaining()

2021-06-28 11:08:40,254 [sfla: INFO] Local Search: 1/5
2021-06-28 11:08:40,469 [sfla: INFO] Local search of Memeplex 1: Mutation 0/2
2021-06-28 11:08:40,473 [sfla: INFO] Memeplex 1.pdb: Learn from local best Pb
2021-06-28 11:08:40,514 [sfla: INFO] Local search of Memeplex 2: Mutation 0/2
2021-06-28 11:08:40,540 [sfla: INFO] Memeplex 2.pdb: Learn from local best Pb
2021-06-28 11:08:40,569 [sfla: INFO] Local search of Memeplex 3: Mutation 0/2
2021-06-28 11:08:40,605 [sfla: INFO] Memeplex 3.pdb: Learn from local best Pb
2021-06-28 11:08:40,631 [sfla: INFO] Local search of Memeplex 4: Mutation 0/2
2021-06-28 11:08:40,669 [sfla: INFO] Memeplex 4.pdb: Learn from local best Pb
2021-06-28 11:08:40,690 [sfla: INFO] Local search of Memeplex 5: Mutation 0/2
2021-06-28 11:08:40,694 [sfla: INFO] Memeplex 5.pdb: Learn from local best Pb
2021-06-28 11:08:40,754 [sfla: INFO] Local search of Memeplex 6: Mutation 0/2
2021-06-28 11:08:40,760 [sfla: INFO] Memeplex 6.pdb: Learn from local best Pb
2021-06-2

In [8]:
model.memeplexes

array([[15., 10., 40., 31., 45.],
       [33.,  7., 30., 44., 18.],
       [29., 24.,  3., 16., 41.],
       [12.,  8., 22., 21.,  5.],
       [13., 11., 36., 23.,  9.],
       [47., 34., 39., 43., 19.],
       [17., 28.,  1., 35., 46.],
       [32., 27.,  2., 49., 26.],
       [48., 14.,  4., 20., 38.],
       [42.,  0.,  6., 25., 37.]])

In [9]:
model.conformation_data[15]

[-76.18173825324475,
 Quaternion(0.7566750526037491, 0.20182174219601048, -0.6086322311546324, 0.12758391882919481),
 array([-31.44959975, -22.07516527,  17.31679871])]

In [10]:
model.conformation_data[33]

[-66.98321332084524,
 Quaternion(0.7688395928601863, 0.19299388730491027, -0.6003810575544001, 0.10574320613345517),
 array([-31.79994894, -21.36398122,  17.06493671])]

In [11]:
model.run_remaining()

2021-06-28 11:17:12,187 [sfla: INFO] Local Search: 1/5
2021-06-28 11:17:12,301 [sfla: INFO] Local search of Memeplex 1: Mutation 0/2
2021-06-28 11:17:12,307 [sfla: INFO] Memeplex 1.pdb: Learn from local best Pb
2021-06-28 11:17:12,350 [sfla: INFO] Local search of Memeplex 2: Mutation 0/2
2021-06-28 11:17:12,393 [sfla: INFO] Memeplex 2.pdb: Learn from local best Pb
2021-06-28 11:17:12,410 [sfla: INFO] Local search of Memeplex 3: Mutation 0/2
2021-06-28 11:17:12,453 [sfla: INFO] Memeplex 3.pdb: Learn from local best Pb
2021-06-28 11:17:12,462 [sfla: INFO] Local search of Memeplex 4: Mutation 0/2
2021-06-28 11:17:12,466 [sfla: INFO] Memeplex 4.pdb: Learn from local best Pb
2021-06-28 11:17:12,510 [sfla: INFO] Local search of Memeplex 5: Mutation 0/2
2021-06-28 11:17:12,515 [sfla: INFO] Memeplex 5.pdb: Learn from local best Pb
2021-06-28 11:17:12,561 [sfla: INFO] Local search of Memeplex 6: Mutation 0/2
2021-06-28 11:17:12,565 [sfla: INFO] Memeplex 6.pdb: Learn from local best Pb
2021-06-2

In [12]:
model.memeplexes

array([[49., 13., 42., 14.,  5.],
       [25., 47., 46.,  0., 21.],
       [15., 17., 44., 30., 23.],
       [33., 10., 41.,  6., 31.],
       [ 4.,  7.,  2.,  3., 37.],
       [40., 24.,  8., 22., 35.],
       [16., 43., 11., 39.,  9.],
       [29., 32., 34.,  1., 38.],
       [12., 45., 28., 36., 18.],
       [20., 48., 27., 26., 19.]])

In [13]:
model.conformation_data[49]

[-129.55929150742196,
 Quaternion(0.8401979738059899, 0.12733415149347374, 0.08893700742899815, -0.519560956371166),
 array([-24.223472  ,  21.65167409,  22.54323875])]

In [14]:
model.conformation_data[25]

[-87.92221064094063,
 Quaternion(0.7996739551703798, 0.20517952028131162, -0.5475203945783959, 0.13654430563011427),
 array([-31.7893288 ,  17.28454869,  21.33840517])]

In [15]:
model.conformation_data[15]

[-76.18173825324475,
 Quaternion(0.7566750526037491, 0.20182174219601048, -0.6086322311546324, 0.12758391882919481),
 array([-31.44959975, -22.07516527,  17.31679871])]

In [16]:
import numpy as np