In [1]:
%reload_ext autoreload
%autoreload 2

In [64]:
from utils import poses

In [154]:
def clip_the_point_max_step(worst_frog_pos, best_frog_pos):
    t = 10/np.linalg.norm(worst_frog_pos - best_frog_pos)
    new_change = (1 - t)*worst_frog_pos + t*best_frog_pos
    return new_change

In [164]:
sfla_1.memeplexes = sfla_1.sort_frog()

In [191]:
new_q, new_t = sfla_1.new_step(sfla_1.structinfo[5][1], sfla_1.structinfo[5][2], sfla_1.structinfo[9][1], sfla_1.structinfo[9][2])

In [192]:
new_q_1, new_t_1 = sfla_1.new_step_test(sfla_1.structinfo[5][1], sfla_1.structinfo[5][2], sfla_1.structinfo[9][1], sfla_1.structinfo[9][2])

In [1]:
%reload_ext autoreload
%autoreload 2

In [1]:
from sfla import SFLA 

In [2]:
model = SFLA(frogs=50, mplx_no=10, no_of_iteration=2, no_of_mutation=2, q=4)

In [3]:
model.run_sfla_test("Data/4dn4_LH:M/", "4dn4", "LH", "M")

2021-06-28 11:06:49,712 [sfla: INFO] Starting SFLA algorithm
2021-06-28 11:06:52,829 [sfla: INFO] Generating initial population (Number of frogs: 50)
2021-06-28 11:07:02,887 [sfla: INFO] out39.pdb -- score = 0.000
2021-06-28 11:07:13,382 [sfla: INFO] out4.pdb -- score = 0.000
2021-06-28 11:07:13,410 [sfla: INFO] out1.pdb -- score = 0.000
2021-06-28 11:07:14,650 [sfla: INFO] out2.pdb -- score = 0.000
2021-06-28 11:07:14,997 [sfla: INFO] out6.pdb -- score = 0.000
2021-06-28 11:07:16,389 [sfla: INFO] out5.pdb -- score = 19704289.106
2021-06-28 11:07:16,803 [sfla: INFO] out10.pdb -- score = 3924011.986
2021-06-28 11:07:17,004 [sfla: INFO] out36.pdb -- score = 0.000
2021-06-28 11:07:17,256 [sfla: INFO] out25.pdb -- score = 31618718.291
2021-06-28 11:07:17,791 [sfla: INFO] out0.pdb -- score = 1001851.241
2021-06-28 11:07:17,892 [sfla: INFO] out20.pdb -- score = 5801502.661
2021-06-28 11:07:17,915 [sfla: INFO] out21.pdb -- score = 25265.738
2021-06-28 11:07:18,838 [sfla: INFO] out7.pdb -- sco

In [4]:
model.memeplexes

array([[15.,  3., 44., 48.,  5.],
       [29., 22.,  9.,  0., 25.],
       [12.,  1., 24., 46., 37.],
       [13.,  2., 26., 32., 17.],
       [47.,  4., 19., 23., 38.],
       [34.,  6., 21., 35., 11.],
       [28., 27., 45., 18., 42.],
       [14., 36.,  7., 10.,  8.],
       [40., 39., 43., 20., 33.],
       [30., 31., 41., 16., 49.]])

In [5]:
model.conformation_data[15]

[-76.18173825324475,
 Quaternion(0.7566750526037491, 0.20182174219601048, -0.6086322311546324, 0.12758391882919481),
 array([-31.44959975, -22.07516527,  17.31679871])]

In [6]:
model.conformation_data[29]

[-24.39316901117409,
 Quaternion(0.48637570542402786, 0.804120104886761, 0.32360681410431974, 0.11003708445535995),
 array([-18.41405475,   3.98984686,  46.4517414 ])]

In [ ]:
model.run_remaining()

In [8]:
model.memeplexes

array([[15., 10., 40., 31., 45.],
       [33.,  7., 30., 44., 18.],
       [29., 24.,  3., 16., 41.],
       [12.,  8., 22., 21.,  5.],
       [13., 11., 36., 23.,  9.],
       [47., 34., 39., 43., 19.],
       [17., 28.,  1., 35., 46.],
       [32., 27.,  2., 49., 26.],
       [48., 14.,  4., 20., 38.],
       [42.,  0.,  6., 25., 37.]])

In [9]:
model.conformation_data[15]

[-76.18173825324475,
 Quaternion(0.7566750526037491, 0.20182174219601048, -0.6086322311546324, 0.12758391882919481),
 array([-31.44959975, -22.07516527,  17.31679871])]

In [10]:
model.conformation_data[33]

[-66.98321332084524,
 Quaternion(0.7688395928601863, 0.19299388730491027, -0.6003810575544001, 0.10574320613345517),
 array([-31.79994894, -21.36398122,  17.06493671])]

In [ ]:
model.run_remaining()

In [18]:
directory = "native_" + 
final_path = os.path.join("./", directory)
os.mkdir(final_path)

In [20]:
!python sfla.py --pdb Data/4dn4_LH:M -n 1

2021-06-28 20:16:15,447 [__main__: INFO] Starting SFLA algorithm
2021-06-28 20:16:18,667 [__main__: INFO] Generating initial population (Number of frogs: 50)
2021-06-28 20:16:25,797 [__main__: INFO] out3.pdb -- score = 0.000
2021-06-28 20:16:27,066 [__main__: INFO] out20.pdb -- score = 0.000
2021-06-28 20:16:39,861 [__main__: INFO] out6.pdb -- score = 0.000
2021-06-28 20:16:40,434 [__main__: INFO] out5.pdb -- score = 0.000
2021-06-28 20:16:41,515 [__main__: INFO] out12.pdb -- score = 0.000
2021-06-28 20:16:41,531 [__main__: INFO] out25.pdb -- score = 0.000
2021-06-28 20:16:41,644 [__main__: INFO] out16.pdb -- score = 62510200.032
2021-06-28 20:16:41,905 [__main__: INFO] out24.pdb -- score = 0.000
2021-06-28 20:16:42,211 [__main__: INFO] out9.pdb -- score = 325242497.823
2021-06-28 20:16:42,236 [__main__: INFO] out4.pdb -- score = 957986358.151
2021-06-28 20:16:42,984 [__main__: INFO] out38.pdb -- score = 0.000
2021-06-28 20:16:43,028 [__main__: INFO] out27.pdb -- score = 208260731.229


In [ ]:
!./sfladock.sh