In [1]:
%reload_ext autoreload
%autoreload 2

In [64]:
from utils import poses

In [154]:
def clip_the_point_max_step(worst_frog_pos, best_frog_pos):
    t = 10/np.linalg.norm(worst_frog_pos - best_frog_pos)
    new_change = (1 - t)*worst_frog_pos + t*best_frog_pos
    return new_change

In [164]:
sfla_1.memeplexes = sfla_1.sort_frog()

In [191]:
new_q, new_t = sfla_1.new_step(sfla_1.structinfo[5][1], sfla_1.structinfo[5][2], sfla_1.structinfo[9][1], sfla_1.structinfo[9][2])

In [192]:
new_q_1, new_t_1 = sfla_1.new_step_test(sfla_1.structinfo[5][1], sfla_1.structinfo[5][2], sfla_1.structinfo[9][1], sfla_1.structinfo[9][2])

In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
from sfla import SFLA 

In [3]:
model = SFLA(frogs=50, mplx_no=10, no_of_iteration=2, no_of_mutation=2, q=4)

In [4]:
model.run_sfla_test("Data/4dn4_LH:M/", "4dn4", "LH", "M")

2021-06-30 09:43:25,643 [sfla: INFO] Starting SFLA algorithm
2021-06-30 09:43:28,875 [sfla: INFO] Generating initial population (Number of frogs: 50)
2021-06-30 09:43:34,923 [sfla: INFO] out1.pdb -- score = 0.000
2021-06-30 09:43:34,999 [sfla: INFO] out2.pdb -- score = 0.000
2021-06-30 09:43:35,382 [sfla: INFO] out8.pdb -- score = 0.000
2021-06-30 09:43:35,558 [sfla: INFO] out13.pdb -- score = 0.000
2021-06-30 09:43:35,805 [sfla: INFO] out6.pdb -- score = 0.000
2021-06-30 09:43:35,892 [sfla: INFO] out10.pdb -- score = 0.000
2021-06-30 09:43:35,903 [sfla: INFO] out9.pdb -- score = 0.000
2021-06-30 09:43:36,940 [sfla: INFO] out19.pdb -- score = 0.000
2021-06-30 09:43:37,071 [sfla: INFO] out20.pdb -- score = 0.000
2021-06-30 09:43:37,381 [sfla: INFO] out21.pdb -- score = 0.000
2021-06-30 09:43:37,536 [sfla: INFO] out26.pdb -- score = 0.000
2021-06-30 09:43:38,548 [sfla: INFO] out38.pdb -- score = 0.000
2021-06-30 09:43:41,081 [sfla: INFO] out45.pdb -- score = 0.000
2021-06-30 09:43:44,897

In [4]:
model.memeplexes

array([[15.,  3., 44., 48.,  5.],
       [29., 22.,  9.,  0., 25.],
       [12.,  1., 24., 46., 37.],
       [13.,  2., 26., 32., 17.],
       [47.,  4., 19., 23., 38.],
       [34.,  6., 21., 35., 11.],
       [28., 27., 45., 18., 42.],
       [14., 36.,  7., 10.,  8.],
       [40., 39., 43., 20., 33.],
       [30., 31., 41., 16., 49.]])

In [5]:
model.conformation_data[15]

[-76.18173825324475,
 Quaternion(0.7566750526037491, 0.20182174219601048, -0.6086322311546324, 0.12758391882919481),
 array([-31.44959975, -22.07516527,  17.31679871])]

In [6]:
model.conformation_data[29]

[-24.39316901117409,
 Quaternion(0.48637570542402786, 0.804120104886761, 0.32360681410431974, 0.11003708445535995),
 array([-18.41405475,   3.98984686,  46.4517414 ])]

In [ ]:
model.run_remaining()

In [8]:
model.memeplexes

array([[15., 10., 40., 31., 45.],
       [33.,  7., 30., 44., 18.],
       [29., 24.,  3., 16., 41.],
       [12.,  8., 22., 21.,  5.],
       [13., 11., 36., 23.,  9.],
       [47., 34., 39., 43., 19.],
       [17., 28.,  1., 35., 46.],
       [32., 27.,  2., 49., 26.],
       [48., 14.,  4., 20., 38.],
       [42.,  0.,  6., 25., 37.]])

In [9]:
model.conformation_data[15]

[-76.18173825324475,
 Quaternion(0.7566750526037491, 0.20182174219601048, -0.6086322311546324, 0.12758391882919481),
 array([-31.44959975, -22.07516527,  17.31679871])]

In [10]:
model.conformation_data[33]

[-66.98321332084524,
 Quaternion(0.7688395928601863, 0.19299388730491027, -0.6003810575544001, 0.10574320613345517),
 array([-31.79994894, -21.36398122,  17.06493671])]

In [ ]:
model.run_remaining()

In [18]:
directory = "native_" + 
final_path = os.path.join("./", directory)
os.mkdir(final_path)

In [20]:
!python sfla.py --pdb Data/4dn4_LH:M -n 1

2021-06-28 20:16:15,447 [__main__: INFO] Starting SFLA algorithm
2021-06-28 20:16:18,667 [__main__: INFO] Generating initial population (Number of frogs: 50)
2021-06-28 20:16:25,797 [__main__: INFO] out3.pdb -- score = 0.000
2021-06-28 20:16:27,066 [__main__: INFO] out20.pdb -- score = 0.000
2021-06-28 20:16:39,861 [__main__: INFO] out6.pdb -- score = 0.000
2021-06-28 20:16:40,434 [__main__: INFO] out5.pdb -- score = 0.000
2021-06-28 20:16:41,515 [__main__: INFO] out12.pdb -- score = 0.000
2021-06-28 20:16:41,531 [__main__: INFO] out25.pdb -- score = 0.000
2021-06-28 20:16:41,644 [__main__: INFO] out16.pdb -- score = 62510200.032
2021-06-28 20:16:41,905 [__main__: INFO] out24.pdb -- score = 0.000
2021-06-28 20:16:42,211 [__main__: INFO] out9.pdb -- score = 325242497.823
2021-06-28 20:16:42,236 [__main__: INFO] out4.pdb -- score = 957986358.151
2021-06-28 20:16:42,984 [__main__: INFO] out38.pdb -- score = 0.000
2021-06-28 20:16:43,028 [__main__: INFO] out27.pdb -- score = 208260731.229


In [ ]:
!./sfladock.sh

In [46]:
??model.find_score

Signature: model.find_score(args)
Docstring: <no docstring>
Source:   
    def memeplexes(self, memeplexes):
        self._memeplexes = memeplexes
File:      ~/Documents/SFLADock/sfla/sfla.py
Type:      method


In [62]:
from enum import unique
import os, sys, logging
import argparse, shutil
import concurrent.futures

import numpy as np
from Bio.PDB import *
from pyquaternion import Quaternion

from utils.Complex import Complex
from utils import pdbtools
from utils import pdb_resdepth
from utils import matrice_distances
from utils import Lennard_Jones
from utils import electrostatic
from utils import poses

In [68]:
def find_score_test():
    #logger.info(f"out{args[1]}.pdb: Calculating score")
    #output_file = self.write_to_file(args[0], args[1])
    #pdbfile = os.path.join(self.mypath, output_file)
    my_struct = pdbtools.read_pdb('Data/4dn4_LH:M/4dn4_LH:M.pdb')
    try:
        depth_dict = pdb_resdepth.calculate_resdepth(structure=my_struct, pdb_filename='Data/4dn4_LH:M/4dn4_LH:M.pdb', method="msms")
    except:
        return

    distmat = matrice_distances.calc_distance_matrix(
        structure=my_struct,
        depth=depth_dict,
        chain_R=model.receptor.chain,
        chain_L=model.ligand.chain,
        dist_max=8.6,
        method="msms",
    )

    vdw = Lennard_Jones.lennard_jones(dist_matrix=distmat)
    electro = electrostatic.electrostatic(inter_resid_dict=distmat, pH=7)
    score = vdw + electro
    return score


In [60]:
model.receptor.chain

['L', 'H']

In [69]:
res = find_score_test()

In [70]:
res

-16.783977083366942

In [12]:
model.receptor_max_diameter

78.16789874416358

In [13]:
model.ligand_max_diameter

44.166473587230875

In [16]:
import numpy as np

In [17]:
rng = np.random.default_rng(0)

In [21]:
??rng.random

Docstring:
random(size=None, dtype=np.float64, out=None)

Return random floats in the half-open interval [0.0, 1.0).

Results are from the "continuous uniform" distribution over the
stated interval.  To sample :math:`Unif[a, b), b > a` multiply
the output of `random` by `(b-a)` and add `a`::

  (b - a) * random() + a

Parameters
----------
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result, only `float64` and `float32` are supported.
    Byteorder must be native. The default value is np.float64.
out : ndarray, optional
    Alternative output array in which to place the result. If size is not None,
    it must have the same shape as the provided size and must match the type of
    the output values.

Returns
-------
out : float or ndarray of floats
    Array of random floats of 