In [1]:
%reload_ext autoreload
%autoreload 2

In [64]:
from utils import poses

In [154]:
def clip_the_point_max_step(worst_frog_pos, best_frog_pos):
    t = 10/np.linalg.norm(worst_frog_pos - best_frog_pos)
    new_change = (1 - t)*worst_frog_pos + t*best_frog_pos
    return new_change

In [164]:
sfla_1.memeplexes = sfla_1.sort_frog()

In [191]:
new_q, new_t = sfla_1.new_step(sfla_1.structinfo[5][1], sfla_1.structinfo[5][2], sfla_1.structinfo[9][1], sfla_1.structinfo[9][2])

In [192]:
new_q_1, new_t_1 = sfla_1.new_step_test(sfla_1.structinfo[5][1], sfla_1.structinfo[5][2], sfla_1.structinfo[9][1], sfla_1.structinfo[9][2])

In [195]:
final = sfla_1.ligand.tranformation(new_q_1, new_t_1)   #final = np.array([Uq.rotate(i) for i in self.lig_atom])  
results =sfla_1.find_score([final, 101, new_q_1, new_t_1])

MSMS running for poses/out101.pdb
MSMS finished with poses/out101.pdb


In [199]:
np.linalg.norm(new_t_1)

21.182364076911945

In [196]:
results

(46381.94082487143,
 101,
 Quaternion(0.7908955136993902, 0.02198214455782066, -0.22075132550856919, 0.5703244024386703),
 array([ -2.64304872, -20.13472692,   6.02491602]))

In [189]:
sfla_1.structinfo[5]

[-30.397091764806422,
 Quaternion(0.8105213235790795, 0.03500468907997499, -0.07755693990824637, 0.5794952776667813),
 array([ -9.98857793, -18.98548946,  28.15920725])]

In [190]:
sfla_1.structinfo[9]

[48076131.94406144,
 Quaternion(0.5161136363828437, -0.037365014798154295, -0.7602118175000121, 0.3928212857549089),
 array([  0.50284043, -20.62691388,  -3.45459522])]

In [180]:
new_t_1

array([-5.55242414, -1.75247124, 30.52201395])

In [173]:
sfla_1.step_size = 10

In [169]:
sfla_1.structinfo[22]

Quaternion(0.8773262983303337, -0.44705412890200386, 0.05120826949124852, -0.16678994341799044)

In [165]:
sfla_1.memeplexes

array([[39.,  8., 47., 13., 22.],
       [ 5., 11., 44., 42.,  9.],
       [41., 15., 20., 46., 32.],
       [26., 17.,  3.,  1., 19.],
       [ 7., 24., 36., 34., 14.],
       [16., 27., 35., 43.,  0.],
       [18., 28., 38., 37., 48.],
       [33., 31., 10.,  4., 25.],
       [ 6., 40., 21., 49., 23.],
       [29., 45., 12.,  2., 30.]])

In [136]:
recMax

78.16790088800205

In [2]:
from sfla import SFLA 

In [4]:
model = SFLA(frogs=50, mplx_no=10, n_iter=2, N=2, q=4)

In [5]:
model.run_sfla_test("Data/4dn4_LH:M/", "4dn4", "LH", "M")

2021-06-27 22:25:03,857 [sfla: INFO] Starting SFLA algorithm
2021-06-27 22:25:07,008 [sfla: INFO] Generating initial population (Number of frogs: 50)
2021-06-27 22:25:09,197 [sfla: INFO] out0.pdb -- Calculating score
2021-06-27 22:25:09,228 [sfla: INFO] out1.pdb -- Calculating score
2021-06-27 22:25:09,298 [sfla: INFO] out2.pdb -- Calculating score
2021-06-27 22:25:09,379 [sfla: INFO] out4.pdb -- Calculating score
2021-06-27 22:25:09,420 [sfla: INFO] out3.pdb -- Calculating score
2021-06-27 22:25:09,472 [sfla: INFO] out5.pdb -- Calculating score
2021-06-27 22:25:09,522 [sfla: INFO] out6.pdb -- Calculating score
2021-06-27 22:25:09,569 [sfla: INFO] out7.pdb -- Calculating score
2021-06-27 22:25:09,620 [sfla: INFO] out8.pdb -- Calculating score
2021-06-27 22:25:09,668 [sfla: INFO] out9.pdb -- Calculating score
2021-06-27 22:25:09,715 [sfla: INFO] out10.pdb -- Calculating score
2021-06-27 22:25:09,775 [sfla: INFO] out11.pdb -- Calculating score
2021-06-27 22:25:09,855 [sfla: INFO] out12.p

In [6]:
model.structinfo

{0: [4294137.1256010765,
  Quaternion(0.751794692382662, 0.1251349645492385, -0.5843669628423872, -0.2786776522990016),
  array([  5.74358786,  13.3202212 , -41.10594281])],
 1: [29399.037512923052,
  Quaternion(0.34859079403260423, -0.8328395387304101, -0.18936256786264152, -0.38601111245079817),
  array([  7.43761023, -42.05532137, -19.5247726 ])],
 2: [11190.536097897502,
  Quaternion(0.49748836748018643, 0.30281963819043606, -0.3439555220046789, 0.7365461219982095),
  array([ 25.92631142,  16.90272787, -24.80150189])],
 3: [-0.9051237374393946,
  Quaternion(0.9299055068717239, -0.17984277723306039, 0.10349481116318952, -0.30367935035006555),
  array([-8.94099279, 45.38037804, 27.56114958])],
 4: [149811404.5429113,
  Quaternion(0.8158529759570551, 0.3346063850660154, -0.2804423532466054, 0.3791761796323402),
  array([19.34195387, 27.77395111,  5.62584619])],
 5: [-7.46118222533007,
  Quaternion(0.7868945955540179, 0.6111503150520987, 0.0815351183695834, 0.025381339051697028),
  arr

In [7]:
model.memeplexes

array([[44., 22., 43., 21.,  4.],
       [25., 32., 20., 39., 34.],
       [38., 48., 26.,  0., 45.],
       [19.,  3., 16., 11., 24.],
       [13.,  8., 17., 30., 18.],
       [12., 27., 47., 15.,  7.],
       [14., 31.,  2., 37., 23.],
       [ 5., 36., 10., 35., 28.],
       [29., 41., 33., 40.,  6.],
       [ 9., 42.,  1., 49., 46.]])

In [8]:
model.structinfo[44]

[-14.040267729521446,
 Quaternion(0.7780674956908269, 0.3510747929654925, 0.2630546234499461, -0.4496217598996391),
 array([-17.23189383, -10.47103711,  42.93188719])]

In [9]:
model.structinfo[25]

[-13.969511905610304,
 Quaternion(0.8539567263742673, 0.2946050573955068, 0.15633677609347024, -0.399405285490609),
 array([ 31.5494521 ,  -7.46737657, -39.1010524 ])]

In [10]:
model.local_search_test()

2021-06-27 22:27:03,615 [sfla: INFO] Local search of Memeplex 1: Mutation 0/2
2021-06-27 22:27:03,620 [sfla: INFO] out51.pdb: Learn from local best Pb
2021-06-27 22:27:03,670 [sfla: INFO] out51.pdb -- Calculating score
2021-06-27 22:27:03,640 [sfla: INFO] Local search of Memeplex 2: Mutation 0/2
2021-06-27 22:27:03,684 [sfla: INFO] out52.pdb: Learn from local best Pb
2021-06-27 22:27:03,692 [sfla: INFO] Local search of Memeplex 3: Mutation 0/2
2021-06-27 22:27:03,732 [sfla: INFO] out53.pdb: Learn from local best Pb
2021-06-27 22:27:03,738 [sfla: INFO] out52.pdb -- Calculating score
2021-06-27 22:27:03,743 [sfla: INFO] Local search of Memeplex 4: Mutation 0/2
2021-06-27 22:27:03,747 [sfla: INFO] out54.pdb: Learn from local best Pb
2021-06-27 22:27:03,784 [sfla: INFO] out53.pdb -- Calculating score
2021-06-27 22:27:03,795 [sfla: INFO] out54.pdb -- Calculating score
2021-06-27 22:27:03,965 [sfla: INFO] Local search of Memeplex 5: Mutation 0/2
2021-06-27 22:27:03,969 [sfla: INFO] out55.pdb

In [11]:
model.shuffle_memeplexes()

2021-06-27 22:28:04,593 [sfla: INFO] Shuffling the memeplexes and sorting them


In [13]:
model.local_search_test()
model.shuffle_memeplexes()

2021-06-27 22:28:29,305 [sfla: INFO] Local search of Memeplex 1: Mutation 0/2
2021-06-27 22:28:29,309 [sfla: INFO] out51.pdb: Learn from local best Pb
2021-06-27 22:28:29,357 [sfla: INFO] out51.pdb -- Calculating score
2021-06-27 22:28:29,350 [sfla: INFO] Local search of Memeplex 2: Mutation 0/2
2021-06-27 22:28:29,384 [sfla: INFO] out52.pdb: Learn from local best Pb
2021-06-27 22:28:29,439 [sfla: INFO] out52.pdb -- Calculating score
2021-06-27 22:28:29,406 [sfla: INFO] Local search of Memeplex 3: Mutation 0/2
2021-06-27 22:28:29,444 [sfla: INFO] out53.pdb: Learn from local best Pb
2021-06-27 22:28:29,462 [sfla: INFO] Local search of Memeplex 4: Mutation 0/2
2021-06-27 22:28:29,488 [sfla: INFO] out54.pdb: Learn from local best Pb
2021-06-27 22:28:29,490 [sfla: INFO] out53.pdb -- Calculating score
2021-06-27 22:28:29,518 [sfla: INFO] Local search of Memeplex 5: Mutation 0/2
2021-06-27 22:28:29,528 [sfla: INFO] out55.pdb: Learn from local best Pb
2021-06-27 22:28:29,575 [sfla: INFO] out5

In [14]:
model.memeplexes

array([[49., 29., 31.,  2., 34.],
       [44.,  9., 36., 28.,  7.],
       [25., 22., 41., 10., 40.],
       [38., 32., 20.,  1., 46.],
       [19., 48., 26.,  6.,  4.],
       [13.,  3., 18., 45., 15.],
       [12., 42., 16., 35.,  0.],
       [33., 43., 17., 21., 30.],
       [14.,  8., 47., 37., 11.],
       [ 5., 27., 39., 23., 24.]])

In [15]:
model.structinfo[49]

[-35.88677380922011,
 Quaternion(0.7975600280551494, 0.34057353498168685, 0.38800036977142227, -0.3120310593129898),
 array([-18.0720496 ,  -3.51994311,  41.73690574])]

In [8]:
model.structinfo

{0: [18985.675325867676,
  Quaternion(0.9445324007638084, -0.2443205622790747, 0.19880734778805131, -0.09296044976480183),
  array([ -0.74938056,  -6.60606223, -20.72597802])],
 1: [1723.6491373625402,
  Quaternion(0.34859079403260423, -0.8328395387304101, -0.18936256786264152, -0.38601111245079817),
  array([-8.05649544,  9.93897748, 37.95407516])],
 2: [-0.8215530956360935,
  Quaternion(0.49748836748018643, 0.30281963819043606, -0.3439555220046789, 0.7365461219982095),
  array([11.25034828,  6.9709162 , 44.23947301])],
 3: [1970502.492829524,
  Quaternion(0.9299055068717239, -0.17984277723306039, 0.10349481116318952, -0.30367935035006555),
  array([-16.14125857,  30.69321457,  -2.56103246])],
 4: [263388046976.84723,
  Quaternion(0.8685855890332609, 0.2958081142001553, -0.27596854288144146, 0.2861782616429579),
  array([-14.44270937,  -8.75973423,  10.83831042])],
 5: [452.1329220469834,
  Quaternion(0.7868945955540179, 0.6111503150520987, 0.0815351183695834, 0.025381339051697028),
 

In [ ]:
model.local_search_test()

In [27]:
model.run_remaining()

MSMS running for poses/out51.pdb
MSMS running for poses/out52.pdb
MSMS running for poses/out53.pdb
MSMS running for poses/out55.pdb
MSMS running for poses/out54.pdb
MSMS running for poses/out56.pdb
MSMS running for MSMS running forposes/out57.pdb 
poses/out58.pdb
MSMS running for poses/out59.pdb
MSMS running for poses/out60.pdb
MSMS finished with poses/out59.pdb
MSMS finished with poses/out57.pdb
MSMS running for poses/out59.pdb
MSMS finished with poses/out54.pdb
MSMS running for poses/out57.pdb
MSMS running for poses/out54.pdb
MSMS finished with poses/out58.pdb
MSMS finished with poses/out51.pdb
MSMS finished with poses/out60.pdb
MSMS finished with poses/out56.pdb
MSMS finished with MSMS finished withposes/out55.pdb 
poses/out53.pdb
MSMS running for poses/out51.pdb
MSMS running for poses/out58.pdb
MSMS running for poses/out60.pdb
MSMS running for poses/out56.pdb
MSMS finished with poses/out52.pdb
MSMS running for poses/out55.pdb
MSMS running for poses/out53.pdb
MSMS running for poses/

In [23]:
model.memeplexes

array([[ 2., 13., 31., 33., 42.],
       [40., 11., 37., 36., 44.],
       [ 9., 46., 19.,  3., 39.],
       [23., 32., 15., 38.,  1.],
       [35., 18.,  5., 34., 48.],
       [ 4., 27., 16., 22., 12.],
       [49., 10., 43., 20., 28.],
       [29.,  8., 47.,  6., 14.],
       [26., 24., 17.,  0., 25.],
       [ 7., 45., 41., 30., 21.]])

In [28]:
model.memeplexes

array([[ 2., 13., 31., 33., 42.],
       [40.,  8., 37., 36., 44.],
       [ 9., 11., 19.,  3., 39.],
       [23., 26., 15., 38.,  1.],
       [35., 46.,  5., 34., 48.],
       [ 4., 24., 16., 22., 12.],
       [27., 32., 43., 20., 28.],
       [49.,  7., 47.,  6., 14.],
       [10., 18., 17.,  0., 25.],
       [29., 45., 41., 30., 21.]])

In [26]:
model.structinfo[21]

[2.5286548556713836e+18,
 Quaternion(0.7601526864981566, -0.546707780925355, -0.05720738845053106, -0.34641854770202396),
 array([-22.2555501 ,  13.34884421,  11.5181412 ])]

In [21]:
??model.local_search

Signature: model.local_search()
Docstring: <no docstring>
Source:   
    def local_search(self):
        self.Frog_gb = self.structinfo[int(self.memeplexes[0][0])]
        
        with concurrent.futures.ProcessPoolExecutor() as executor:
            doargs = [im for im, _ in enumerate(self.memeplexes)]
            results = executor.map(self.local_search_one_memeplex, doargs)
File:      ~/Documents/SFLADock/src/sfla.py
Type:      method


In [1]:
%reload_ext autoreload
%autoreload 2

In [9]:
from sfla import SFLA 

In [12]:
model = SFLA(frogs=50, mplx_no=10, n_iter=2, N=2, q=4)

In [13]:
model.run_sfla_test("Data/4dn4_LH:M/", "4dn4", "LH", "M")

2021-06-27 21:58:08,412 [sfla: INFO] Starting SFLA algorithm
2021-06-27 21:58:11,552 [sfla: INFO] Generating initial population (Number of frogs: 50)


PicklingError: Can't pickle <class 'sfla.SFLA'>: it's not the same object as sfla.SFLA

In [12]:
model.memeplexes

array([[ 9., 38., 40., 37., 47.],
       [26., 12., 44., 11., 14.],
       [48., 25., 46., 31., 27.],
       [29., 18., 24.,  7., 28.],
       [41., 16., 10., 43., 17.],
       [20.,  6., 42., 49.,  0.],
       [21.,  8., 22.,  2., 32.],
       [15., 13., 19., 36.,  4.],
       [35., 23., 39., 30.,  1.],
       [34., 33.,  5., 45.,  3.]])

In [13]:
model.structinfo[9]

[-34.84959725176546,
 Quaternion(0.41498288162420527, 0.7851384795532247, 0.3167706306816045, 0.3331713424370412),
 array([  6.10511068, -22.40102834, -34.4306511 ])]

In [ ]:
model.run_remaining()

In [16]:
model.memeplexes

array([[ 9., 38., 44., 37., 47.],
       [26., 12., 46., 11., 14.],
       [48., 25.,  6., 31., 27.],
       [29., 18., 24.,  7., 28.],
       [41., 16., 10., 43., 17.],
       [20.,  8., 42., 49.,  0.],
       [21., 13., 22.,  2., 32.],
       [15., 23., 19., 36.,  4.],
       [35., 33., 39., 30.,  1.],
       [34., 40.,  5., 45.,  3.]])

In [17]:
model.structinfo[9]

[-34.84959725176546,
 Quaternion(0.41498288162420527, 0.7851384795532247, 0.3167706306816045, 0.3331713424370412),
 array([  6.10511068, -22.40102834, -34.4306511 ])]

In [20]:
import numpy as np

In [21]:
np.argsort(model.memeplexes[1])

array([3, 1, 4, 0, 2])

In [26]:
model.structinfo[tuple(int(model.memeplexes[1]))]

TypeError: only size-1 arrays can be converted to Python scalars

In [ ]:
model.structinfo

In [122]:
model.local_search()

In [122]:


model.local_search_test()

In [45]:
model.N = 1

In [48]:
structinfo = model.structinfo

In [57]:
model.structinfo = structinfo

In [67]:
model.structinfo = structinfo[1], 0

In [69]:
a, b, c = structinfo[1]

In [118]:
model.structinfo

([5239320.152353539,
  Quaternion(0.49748836748018643, 0.30281963819043606, -0.3439555220046789, 0.7365461219982095),
  array([-18.46512394,   6.05021466,  25.81849152])],
 3)

In [120]:
model.structinfo = structinfo

In [121]:
model.structinfo

{0: [155812198755.02823,
  Quaternion(0.34859079403260423, -0.8328395387304101, -0.18936256786264152, -0.38601111245079817),
  array([-7.52617866, -6.76761775, -2.73844473])],
 1: [155812198755.02823,
  Quaternion(0.34859079403260423, -0.8328395387304101, -0.18936256786264152, -0.38601111245079817),
  array([-7.52617866, -6.76761775, -2.73844473])],
 2: [5239320.152353539,
  Quaternion(0.49748836748018643, 0.30281963819043606, -0.3439555220046789, 0.7365461219982095),
  array([-18.46512394,   6.05021466,  25.81849152])],
 3: [687721081911.8915,
  Quaternion(0.9299055068717239, -0.17984277723306039, 0.10349481116318952, -0.30367935035006555),
  array([ 13.87006198, -16.55059817, -15.90504785])],
 4: [20365356487.40301,
  Quaternion(0.8158529759570551, 0.3346063850660154, -0.2804423532466054, 0.3791761796323402),
  array([-22.5427844 ,  -5.19799272,  12.7147298 ])],
 5: [390492.6127025793,
  Quaternion(0.7868945955540179, 0.6111503150520987, 0.0815351183695834, 0.025381339051697028),
  a

In [97]:
model.structinfo

{0: [155812198755.02823,
  Quaternion(0.34859079403260423, -0.8328395387304101, -0.18936256786264152, -0.38601111245079817),
  array([-7.52617866, -6.76761775, -2.73844473])],
 1: [155812198755.02823,
  Quaternion(0.34859079403260423, -0.8328395387304101, -0.18936256786264152, -0.38601111245079817),
  array([-7.52617866, -6.76761775, -2.73844473])],
 2: [5239320.152353539,
  Quaternion(0.49748836748018643, 0.30281963819043606, -0.3439555220046789, 0.7365461219982095),
  array([-18.46512394,   6.05021466,  25.81849152])],
 3: [687721081911.8915,
  Quaternion(0.9299055068717239, -0.17984277723306039, 0.10349481116318952, -0.30367935035006555),
  array([ 13.87006198, -16.55059817, -15.90504785])],
 4: [20365356487.40301,
  Quaternion(0.8158529759570551, 0.3346063850660154, -0.2804423532466054, 0.3791761796323402),
  array([-22.5427844 ,  -5.19799272,  12.7147298 ])],
 5: [390492.6127025793,
  Quaternion(0.7868945955540179, 0.6111503150520987, 0.0815351183695834, 0.025381339051697028),
  a