In [1]:
%reload_ext autoreload
%autoreload 2

In [64]:
from utils import poses

In [154]:
def clip_the_point_max_step(worst_frog_pos, best_frog_pos):
    t = 10/np.linalg.norm(worst_frog_pos - best_frog_pos)
    new_change = (1 - t)*worst_frog_pos + t*best_frog_pos
    return new_change

In [164]:
sfla_1.memeplexes = sfla_1.sort_frog()

In [191]:
new_q, new_t = sfla_1.new_step(sfla_1.structinfo[5][1], sfla_1.structinfo[5][2], sfla_1.structinfo[9][1], sfla_1.structinfo[9][2])

In [192]:
new_q_1, new_t_1 = sfla_1.new_step_test(sfla_1.structinfo[5][1], sfla_1.structinfo[5][2], sfla_1.structinfo[9][1], sfla_1.structinfo[9][2])

In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
from sfla_dfire import SFLA 

In [3]:
model = SFLA(frogs=100, mplx_no=20, no_of_iteration=2, no_of_mutation=3, q=4)

In [4]:
model.run_sfla_test("Data/4dn4_LH:M/", "4dn4", "LH", "M")

2021-07-14 17:52:08,303 [sfla_dfire: INFO] Starting SFLA algorithm
2021-07-14 17:52:11,569 [.prody: DEBUG] 3208 atoms and 1 coordinate set(s) were parsed in 0.02s.
2021-07-14 17:52:11,764 [.prody: DEBUG] Hessian was built in 0.19s.
2021-07-14 17:52:12,093 [.prody: DEBUG] 10 modes were calculated in 0.33s.
2021-07-14 17:52:12,215 [.prody: DEBUG] 568 atoms and 1 coordinate set(s) were parsed in 0.00s.
2021-07-14 17:52:12,234 [.prody: DEBUG] Hessian was built in 0.02s.
2021-07-14 17:52:12,251 [.prody: DEBUG] 10 modes were calculated in 0.02s.
2021-07-14 17:52:12,695 [sfla_dfire: INFO] Generating initial population (Number of frogs: 100)
2021-07-14 17:52:20,577 [sfla_dfire: INFO] out0.pdb -- score = -20.637
2021-07-14 17:52:20,615 [sfla_dfire: INFO] out1.pdb -- score = -0.816
2021-07-14 17:52:20,770 [sfla_dfire: INFO] out3.pdb -- score = 4.700
2021-07-14 17:52:20,820 [sfla_dfire: INFO] out2.pdb -- score = -111.559
2021-07-14 17:52:20,955 [sfla_dfire: INFO] out4.pdb -- score = 4.700
2021-07

In [5]:
model.memeplexes

array([[82., 60.,  9., 79.,  0.],
       [94., 93., 14., 86., 80.],
       [58., 55., 18., 90., 99.],
       [28., 20., 19., 91., 83.],
       [56., 32., 24., 96., 74.],
       [67., 21., 27., 98., 37.],
       [85., 63., 36.,  6.,  7.],
       [69., 11., 38.,  8., 92.],
       [29., 84., 40.,  1., 22.],
       [30., 89., 41., 54., 61.],
       [97., 77., 45., 39., 10.],
       [62., 43., 48., 64.,  2.],
       [57., 87., 49., 23., 73.],
       [35., 42., 51., 52., 25.],
       [50., 88., 53., 31., 13.],
       [66., 47., 59., 81., 34.],
       [95., 12., 65., 46., 17.],
       [33.,  3., 70., 71., 78.],
       [16.,  4., 72., 44., 26.],
       [68.,  5., 76., 15., 75.]])

In [6]:
model.conformation_data[82]

[13.372447840969574,
 Quaternion(0.9605679510531117, 0.2030598683358383, 0.18982649848086114, -0.006465427716300847),
 array([-18.81475503,  75.57770281, -22.00297556]),
 array([0.51017437, 3.93229731, 5.        , 5.        , 4.95307428,
        4.92234409, 4.40557508, 0.27621759, 3.07269344, 5.        ]),
 array([0.1       , 5.        , 5.        , 0.74746087, 1.7609497 ,
        3.38847611, 5.        , 2.87792006, 5.        , 5.        ])]

In [8]:
model.conformation_data[40]

[8.085441050007695,
 Quaternion(0.914680011161885, 0.24623805669721005, 0.30116086839441053, 0.10967874891153727),
 array([-68.81960185,  63.25209024, -26.56110847]),
 array([1.02671265, 4.06511152, 1.23434653, 5.        , 3.6903432 ,
        4.11957525, 1.3264289 , 5.        , 5.        , 5.        ]),
 array([5.        , 3.84244185, 5.        , 3.62851658, 5.        ,
        5.        , 4.79377529, 5.        , 3.08819086, 4.12279684])]

In [9]:
model.conformation_data[17]

[-145.3908532741977,
 Quaternion(0.9962622422849342, 0.053807149746766175, 0.04641123364512675, 0.04911550289940541),
 array([-36.74734538,  53.42226707,  -5.20535417]),
 array([4.65635797, 5.        , 5.        , 0.1       , 5.        ,
        5.        , 2.86239681, 1.54402045, 1.09296271, 4.37013531]),
 array([2.05595112, 1.7053781 , 5.        , 5.        , 2.81628622,
        5.        , 5.        , 0.71651106, 2.19012435, 5.        ])]

In [7]:
model.run_remaining()

2021-07-14 17:57:06,555 [sfla_dfire: INFO] Local Search: 1/5
2021-07-14 17:57:06,931 [sfla_dfire: INFO] Iteration 0 -- Local search of Memeplex 1: Mutation 1/3
2021-07-14 17:57:06,936 [sfla_dfire: INFO] Iteration 0 -- Memeplex 1(out101.pdb): Learn from local best Pb
2021-07-14 17:57:07,066 [sfla_dfire: INFO] Iteration 0 -- Local search of Memeplex 2: Mutation 1/3
2021-07-14 17:57:07,107 [sfla_dfire: INFO] Iteration 0 -- Memeplex 2(out102.pdb): Learn from local best Pb
2021-07-14 17:57:07,183 [sfla_dfire: INFO] out101.pdb -- score = -6.566
2021-07-14 17:57:07,185 [sfla_dfire: INFO] Iteration 0 -- Local search of Memeplex 1: pose moved to out0.pdb ::: Mutation 1/3 finished
2021-07-14 17:57:07,186 [sfla_dfire: INFO] Iteration 0 -- Local search of Memeplex 1: Mutation 2/3
2021-07-14 17:57:07,188 [sfla_dfire: INFO] Iteration 0 -- Memeplex 1(out101.pdb): Learn from local best Pb
2021-07-14 17:57:07,168 [sfla_dfire: INFO] Iteration 0 -- Local search of Memeplex 3: Mutation 1/3
2021-07-14 17:5

In [8]:
model.memeplexes

array([[82., 85., 93., 23., 65.],
       [71., 69., 48., 47., 53.],
       [15., 29., 55., 12., 45.],
       [ 0., 30., 20.,  8., 17.],
       [80., 64., 32.,  7., 24.],
       [94., 97., 21.,  5., 19.],
       [31., 62., 63., 79., 18.],
       [46., 57., 11., 90., 39.],
       [58., 35., 84., 70.,  9.],
       [28., 22., 89., 26.,  3.],
       [56., 50., 77., 51., 38.],
       [ 1., 66.,  6., 41., 14.],
       [67., 95., 43., 49., 72.],
       [81., 33., 87., 76., 25.],
       [13., 16., 96., 34., 59.],
       [78., 68., 40., 83., 91.],
       [75., 60., 42., 27., 10.],
       [44., 74., 86., 99., 98.],
       [52., 37., 88., 54., 92.],
       [61.,  2., 36.,  4., 73.]])

In [9]:
model.conformation_data[82]

[13.372447840969574,
 Quaternion(0.9605679510531117, 0.2030598683358383, 0.18982649848086114, -0.006465427716300847),
 array([-18.81475503,  75.57770281, -22.00297556]),
 array([0.51017437, 3.93229731, 5.        , 5.        , 4.95307428,
        4.92234409, 4.40557508, 0.27621759, 3.07269344, 5.        ]),
 array([0.1       , 5.        , 5.        , 0.74746087, 1.7609497 ,
        3.38847611, 5.        , 2.87792006, 5.        , 5.        ])]

In [13]:
model.run_remaining()

2021-07-14 17:02:23,368 [sfla_dfire: INFO] Local Search: 1/5
2021-07-14 17:02:23,737 [sfla_dfire: INFO] Iteration 0 -- Local search of Memeplex 1: Mutation 1/3
2021-07-14 17:02:23,741 [sfla_dfire: INFO] Iteration 0 -- Memeplex 1(out101.pdb): Learn from local best Pb
2021-07-14 17:02:23,776 [sfla_dfire: INFO] Iteration 0 -- Local search of Memeplex 2: Mutation 1/3
2021-07-14 17:02:23,780 [sfla_dfire: INFO] Iteration 0 -- Memeplex 2(out102.pdb): Learn from local best Pb
2021-07-14 17:02:23,859 [sfla_dfire: INFO] out101.pdb -- score = 4.700
2021-07-14 17:02:23,861 [sfla_dfire: INFO] Iteration 0 -- Local search of Memeplex 1: pose moved to out56.pdb ::: Mutation 1/3 finished
2021-07-14 17:02:23,862 [sfla_dfire: INFO] Iteration 0 -- Local search of Memeplex 1: Mutation 2/3
2021-07-14 17:02:23,864 [sfla_dfire: INFO] Iteration 0 -- Memeplex 1(out101.pdb): Learn from local best Pb
2021-07-14 17:02:23,887 [sfla_dfire: INFO] out102.pdb -- score = 4.700
2021-07-14 17:02:23,889 [sfla_dfire: INFO] 

In [14]:
model.memeplexes

array([[91., 88., 78.,  7., 36.],
       [ 0., 20., 77.,  9., 93.],
       [40., 66., 85., 79.,  4.],
       [98., 84., 31., 83., 28.],
       [22., 34.,  6., 94.,  3.],
       [99., 46., 73., 95.,  5.],
       [64.,  2., 48., 90., 68.],
       [23., 76., 16.,  1., 61.],
       [17., 19., 24.,  8., 21.],
       [67., 27., 50., 26., 62.],
       [53., 57., 10., 12., 13.],
       [89., 86., 55., 42., 44.],
       [45., 97., 47., 60., 11.],
       [32., 43., 96., 56., 14.],
       [71., 54., 25., 49., 52.],
       [37., 74., 65., 18., 58.],
       [72., 30., 92., 15., 39.],
       [82., 80., 41., 70., 38.],
       [75., 29., 81., 35., 87.],
       [51., 69., 59., 33., 63.]])

In [18]:
model.receptor

Complex: name = LH_model_st, pdb_file_name = LH_model_st1.pdb

In [15]:
model.conformation_data[91]

[13.473918486651154,
 Quaternion(0.9491333765779235, 0.21760254099124177, 0.19335432307067785, 0.12003779975417932),
 array([-44.80264895,  65.42727462, -29.5939925 ]),
 array([2.87992466, 3.87584253, 3.11606841, 2.08018165, 3.03748189,
        3.49621107, 2.68654145, 2.71708082, 1.15067638, 4.38643631]),
 array([3.41554302, 3.29721418, 3.36765824, 4.08668061, 3.61343273,
        3.13274507, 3.05165755, 3.04585074, 3.756782  , 1.41638826])]

In [16]:
model.conformation_data[0]

[9.395593071718874,
 Quaternion(0.9325063258602275, 0.2393408042015159, 0.2163300480352262, 0.1623244959699784),
 array([-47.79796275,  71.48277761, -27.96237423]),
 array([3.60368541, 5.        , 4.31470035, 2.39299188, 5.        ,
        5.        , 5.        , 1.88879429, 0.20373559, 2.13017661]),
 array([4.12397794, 0.1       , 3.34362501, 0.26226716, 1.80319794,
        2.36722305, 3.05109953, 5.        , 5.        , 3.61439601])]

In [17]:
model.conformation_data[40]

[8.085441050007695,
 Quaternion(0.914680011161885, 0.24623805669721005, 0.30116086839441053, 0.10967874891153727),
 array([-68.81960185,  63.25209024, -26.56110847]),
 array([1.02671265, 4.06511152, 1.23434653, 5.        , 3.6903432 ,
        4.11957525, 1.3264289 , 5.        , 5.        , 5.        ]),
 array([5.        , 3.84244185, 5.        , 3.62851658, 5.        ,
        5.        , 4.79377529, 5.        , 3.08819086, 4.12279684])]

In [15]:
model.conformation_data[44]

[-80.68445567144957,
 Quaternion(0.9773423245966427, 0.1620163634472336, 0.13522585617381058, 0.01632930952074702),
 array([-39.80195401,  55.98572629, -11.75767417]),
 array([2.27801232, 4.3743068 , 3.01134131, 3.37675141, 2.38321438,
        3.31018094, 1.64711368, 1.96638862, 3.10012968, 1.51862398]),
 array([4.29487287, 3.91048795, 3.93593368, 2.60781954, 3.64561904,
        2.22151864, 3.64338902, 4.09864432, 3.87638159, 1.41524264])]

In [7]:
model.conformation_data[57]

[8.163792759732953,
 Quaternion(0.8735509251268793, 0.22396963466117495, 0.2562735720319465, 0.3479514912135025),
 array([-26.20814951,  78.99814196, -30.83799618]),
 array([5.        , 5.        , 4.92032591, 4.80127588, 0.48001907,
        0.1       , 4.91167002, 5.        , 2.90759572, 0.19432115]),
 array([0.1       , 1.95804486, 5.        , 3.37678139, 0.88616988,
        2.17158747, 2.54936509, 4.79684025, 2.01995064, 1.33018128])]

In [8]:
model.conformation_data[5]

[-158.1227221631908,
 Quaternion(0.9628670605889058, 0.1696335533704646, 0.2100112814043748, 0.00259670689195653),
 array([-27.31520487,  61.48332329,  -7.76252339]),
 array([1.86079571, 5.        , 0.1       , 5.        , 2.25507749,
        4.32783909, 3.77289542, 4.60634319, 5.        , 1.72489075]),
 array([5.        , 5.        , 5.        , 5.        , 5.        ,
        5.        , 4.22678083, 0.1       , 3.5948647 , 1.69145608])]

In [ ]:
!./DockQ.py 

In [19]:
!./DockQ.py "Data/4dn4_LH:M/4dn4_LH:M.pdb" "poses/out32.pdb" -native_chain1 L H

****************************************************************
*                       DockQ                                  *
*   Scoring function for protein-protein docking models        *
*   Statistics on CAPRI data:                                  *
*    0.00 <= DockQ <  0.23 - Incorrect                         *
*    0.23 <= DockQ <  0.49 - Acceptable quality                *
*    0.49 <= DockQ <  0.80 - Medium quality                    *
*            DockQ >= 0.80 - High quality                      *
*   Reference: Sankar Basu and Bjorn Wallner, DockQ: A quality *
*   measure for protein-protein docking models, submitted      *
*                                                              *
*   For the record:                                            *
*   Definition of contact <5A (Fnat)                           *
*   Definition of interface <10A all heavy atoms (iRMS)        *
*   For comments, please email: bjorn.wallner@.liu.se          *
*                        

In [8]:
score = model.dfire_model(model.receptor, model.receptor.atom_coord, model.ligand, model.ligand.atom_coord)

In [9]:
score

10.182681139725752

In [4]:
model.run_sfla_test("Data/4dn4_LH:M/", "4dn4", "LH", "M")

2021-07-04 20:52:07,001 [sfla_dfire: INFO] Starting SFLA algorithm
2021-07-04 20:52:14,126 [sfla_dfire: INFO] Generating initial population (Number of frogs: 50)
2021-07-04 20:52:18,040 [sfla_dfire: INFO] out0.pdb -- score = 4.700
2021-07-04 20:52:18,467 [sfla_dfire: INFO] out1.pdb -- score = 4.704
2021-07-04 20:52:18,753 [sfla_dfire: INFO] out2.pdb -- score = 4.747
2021-07-04 20:52:18,951 [sfla_dfire: INFO] out3.pdb -- score = -99.576
2021-07-04 20:52:19,074 [sfla_dfire: INFO] out4.pdb -- score = 4.708
2021-07-04 20:52:19,104 [sfla_dfire: INFO] out6.pdb -- score = 8.275
2021-07-04 20:52:19,402 [sfla_dfire: INFO] out7.pdb -- score = 4.737
2021-07-04 20:52:19,421 [sfla_dfire: INFO] out8.pdb -- score = 4.705
2021-07-04 20:52:19,627 [sfla_dfire: INFO] out5.pdb -- score = -196.660
2021-07-04 20:52:19,661 [sfla_dfire: INFO] out10.pdb -- score = 4.700
2021-07-04 20:52:19,784 [sfla_dfire: INFO] out9.pdb -- score = -66.780
2021-07-04 20:52:19,787 [sfla_dfire: INFO] out11.pdb -- score = 4.700
2

In [4]:
model.memeplexes

array([[15.,  3., 44., 48.,  5.],
       [29., 22.,  9.,  0., 25.],
       [12.,  1., 24., 46., 37.],
       [13.,  2., 26., 32., 17.],
       [47.,  4., 19., 23., 38.],
       [34.,  6., 21., 35., 11.],
       [28., 27., 45., 18., 42.],
       [14., 36.,  7., 10.,  8.],
       [40., 39., 43., 20., 33.],
       [30., 31., 41., 16., 49.]])

In [5]:
model.conformation_data[15]

[-76.18173825324475,
 Quaternion(0.7566750526037491, 0.20182174219601048, -0.6086322311546324, 0.12758391882919481),
 array([-31.44959975, -22.07516527,  17.31679871])]

In [6]:
model.conformation_data[29]

[-24.39316901117409,
 Quaternion(0.48637570542402786, 0.804120104886761, 0.32360681410431974, 0.11003708445535995),
 array([-18.41405475,   3.98984686,  46.4517414 ])]

In [ ]:
model.run_remaining()

In [8]:
model.memeplexes

array([[15., 10., 40., 31., 45.],
       [33.,  7., 30., 44., 18.],
       [29., 24.,  3., 16., 41.],
       [12.,  8., 22., 21.,  5.],
       [13., 11., 36., 23.,  9.],
       [47., 34., 39., 43., 19.],
       [17., 28.,  1., 35., 46.],
       [32., 27.,  2., 49., 26.],
       [48., 14.,  4., 20., 38.],
       [42.,  0.,  6., 25., 37.]])

In [9]:
model.conformation_data[15]

[-76.18173825324475,
 Quaternion(0.7566750526037491, 0.20182174219601048, -0.6086322311546324, 0.12758391882919481),
 array([-31.44959975, -22.07516527,  17.31679871])]

In [10]:
model.conformation_data[33]

[-66.98321332084524,
 Quaternion(0.7688395928601863, 0.19299388730491027, -0.6003810575544001, 0.10574320613345517),
 array([-31.79994894, -21.36398122,  17.06493671])]

In [ ]:
model.run_remaining()

In [18]:
directory = "native_" + 
final_path = os.path.join("./", directory)
os.mkdir(final_path)

In [20]:
!python sfla.py --pdb Data/4dn4_LH:M -n 1

2021-06-28 20:16:15,447 [__main__: INFO] Starting SFLA algorithm
2021-06-28 20:16:18,667 [__main__: INFO] Generating initial population (Number of frogs: 50)
2021-06-28 20:16:25,797 [__main__: INFO] out3.pdb -- score = 0.000
2021-06-28 20:16:27,066 [__main__: INFO] out20.pdb -- score = 0.000
2021-06-28 20:16:39,861 [__main__: INFO] out6.pdb -- score = 0.000
2021-06-28 20:16:40,434 [__main__: INFO] out5.pdb -- score = 0.000
2021-06-28 20:16:41,515 [__main__: INFO] out12.pdb -- score = 0.000
2021-06-28 20:16:41,531 [__main__: INFO] out25.pdb -- score = 0.000
2021-06-28 20:16:41,644 [__main__: INFO] out16.pdb -- score = 62510200.032
2021-06-28 20:16:41,905 [__main__: INFO] out24.pdb -- score = 0.000
2021-06-28 20:16:42,211 [__main__: INFO] out9.pdb -- score = 325242497.823
2021-06-28 20:16:42,236 [__main__: INFO] out4.pdb -- score = 957986358.151
2021-06-28 20:16:42,984 [__main__: INFO] out38.pdb -- score = 0.000
2021-06-28 20:16:43,028 [__main__: INFO] out27.pdb -- score = 208260731.229


In [ ]:
!./sfladock.sh

In [46]:
??model.find_score

Signature: model.find_score(args)
Docstring: <no docstring>
Source:   
    def memeplexes(self, memeplexes):
        self._memeplexes = memeplexes
File:      ~/Documents/SFLADock/sfla/sfla.py
Type:      method


In [62]:
from enum import unique
import os, sys, logging
import argparse, shutil
import concurrent.futures

import numpy as np
from Bio.PDB import *
from pyquaternion import Quaternion

from utils.Complex import Complex
from utils import pdbtools
from utils import pdb_resdepth
from utils import matrice_distances
from utils import Lennard_Jones
from utils import electrostatic
from utils import poses

In [68]:
def find_score_test():
    #logger.info(f"out{args[1]}.pdb: Calculating score")
    #output_file = self.write_to_file(args[0], args[1])
    #pdbfile = os.path.join(self.mypath, output_file)
    my_struct = pdbtools.read_pdb('Data/4dn4_LH:M/4dn4_LH:M.pdb')
    try:
        depth_dict = pdb_resdepth.calculate_resdepth(structure=my_struct, pdb_filename='Data/4dn4_LH:M/4dn4_LH:M.pdb', method="msms")
    except:
        return

    distmat = matrice_distances.calc_distance_matrix(
        structure=my_struct,
        depth=depth_dict,
        chain_R=model.receptor.chain,
        chain_L=model.ligand.chain,
        dist_max=8.6,
        method="msms",
    )

    vdw = Lennard_Jones.lennard_jones(dist_matrix=distmat)
    electro = electrostatic.electrostatic(inter_resid_dict=distmat, pH=7)
    score = vdw + electro
    return score


In [60]:
model.receptor.chain

['L', 'H']

In [69]:
res = find_score_test()

In [70]:
res

-16.783977083366942

In [12]:
model.receptor_max_diameter

78.16789874416358

In [13]:
model.ligand_max_diameter

44.166473587230875

In [16]:
import numpy as np

In [17]:
rng = np.random.default_rng(0)

In [21]:
??rng.random

Docstring:
random(size=None, dtype=np.float64, out=None)

Return random floats in the half-open interval [0.0, 1.0).

Results are from the "continuous uniform" distribution over the
stated interval.  To sample :math:`Unif[a, b), b > a` multiply
the output of `random` by `(b-a)` and add `a`::

  (b - a) * random() + a

Parameters
----------
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result, only `float64` and `float32` are supported.
    Byteorder must be native. The default value is np.float64.
out : ndarray, optional
    Alternative output array in which to place the result. If size is not None,
    it must have the same shape as the provided size and must match the type of
    the output values.

Returns
-------
out : float or ndarray of floats
    Array of random floats of 