In [9]:
%reload_ext autoreload
%autoreload 2

In [64]:
from utils import poses

In [154]:
def clip_the_point_max_step(worst_frog_pos, best_frog_pos):
    t = 10/np.linalg.norm(worst_frog_pos - best_frog_pos)
    new_change = (1 - t)*worst_frog_pos + t*best_frog_pos
    return new_change

In [164]:
sfla_1.memeplexes = sfla_1.sort_frog()

In [191]:
new_q, new_t = sfla_1.new_step(sfla_1.structinfo[5][1], sfla_1.structinfo[5][2], sfla_1.structinfo[9][1], sfla_1.structinfo[9][2])

In [192]:
new_q_1, new_t_1 = sfla_1.new_step_test(sfla_1.structinfo[5][1], sfla_1.structinfo[5][2], sfla_1.structinfo[9][1], sfla_1.structinfo[9][2])

In [195]:
final = sfla_1.ligand.tranformation(new_q_1, new_t_1)   #final = np.array([Uq.rotate(i) for i in self.lig_atom])  
results =sfla_1.find_score([final, 101, new_q_1, new_t_1])

MSMS running for poses/out101.pdb
MSMS finished with poses/out101.pdb


In [199]:
np.linalg.norm(new_t_1)

21.182364076911945

In [196]:
results

(46381.94082487143,
 101,
 Quaternion(0.7908955136993902, 0.02198214455782066, -0.22075132550856919, 0.5703244024386703),
 array([ -2.64304872, -20.13472692,   6.02491602]))

In [189]:
sfla_1.structinfo[5]

[-30.397091764806422,
 Quaternion(0.8105213235790795, 0.03500468907997499, -0.07755693990824637, 0.5794952776667813),
 array([ -9.98857793, -18.98548946,  28.15920725])]

In [190]:
sfla_1.structinfo[9]

[48076131.94406144,
 Quaternion(0.5161136363828437, -0.037365014798154295, -0.7602118175000121, 0.3928212857549089),
 array([  0.50284043, -20.62691388,  -3.45459522])]

In [180]:
new_t_1

array([-5.55242414, -1.75247124, 30.52201395])

In [173]:
sfla_1.step_size = 10

In [169]:
sfla_1.structinfo[22]

Quaternion(0.8773262983303337, -0.44705412890200386, 0.05120826949124852, -0.16678994341799044)

In [165]:
sfla_1.memeplexes

array([[39.,  8., 47., 13., 22.],
       [ 5., 11., 44., 42.,  9.],
       [41., 15., 20., 46., 32.],
       [26., 17.,  3.,  1., 19.],
       [ 7., 24., 36., 34., 14.],
       [16., 27., 35., 43.,  0.],
       [18., 28., 38., 37., 48.],
       [33., 31., 10.,  4., 25.],
       [ 6., 40., 21., 49., 23.],
       [29., 45., 12.,  2., 30.]])

In [136]:
recMax

78.16790088800205

In [1]:
from sfla import SFLA 

In [2]:
model = SFLA(frogs=50, mplx_no=10, n_iter=2, N=2, q=4)

In [3]:
model.run_sfla_test("Data/4dn4_LH:M/", "4dn4", "LH", "M")

MSMS running for poses/out0.pdb

poses/out1.pdb MSMS running forMSMS running for poses/out2.pdb
MSMS running for 
poses/out4.pdb
MSMS running for poses/out3.pdb
MSMS running for poses/out5.pdb

poses/out7.pdbposes/out6.pdb  MSMS running for
poses/out8.pdb MSMS running forMSMS running forMSMS running for poses/out9.pdb
MSMS running for poses/out10.pdb
MSMS running for poses/out11.pdb
MSMS running for poses/out12.pdb
MSMS running for poses/out13.pdb

poses/out15.pdb MSMS running forMSMS running for poses/out14.pdb
MSMS running for poses/out16.pdb
MSMS running for poses/out17.pdb
MSMS running for poses/out18.pdb
MSMS running for poses/out19.pdb
MSMS running for poses/out20.pdb
MSMS running for poses/out21.pdb

poses/out22.pdb MSMS running forMSMS running for
 poses/out23.pdb
MSMS running for poses/out24.pdbMSMS running for poses/out25.pdb
MSMS running for poses/out26.pdb

poses/out27.pdb MSMS running forMSMS running for poses/out28.pdb
MSMS running for poses/out29.pdb
MSMS running for pos

In [15]:
model.structinfo

{0: [2666123638.572336,
  Quaternion(0.751794692382662, 0.1251349645492385, -0.5843669628423872, -0.2786776522990016),
  array([-26.85428309, -14.99056923,   9.60549515])],
 1: [27880786731.304863,
  Quaternion(0.34859079403260423, -0.8328395387304101, -0.18936256786264152, -0.38601111245079817),
  array([ -3.22117135,   3.47670906, -13.73307849])],
 2: [-56.185603402694554,
  Quaternion(0.49748836748018643, 0.30281963819043606, -0.3439555220046789, 0.7365461219982095),
  array([ -7.86895169,  19.20295601, -22.11289477])],
 3: [714935944.0329845,
  Quaternion(0.9299055068717239, -0.17984277723306039, 0.10349481116318952, -0.30367935035006555),
  array([  4.32225825,  18.31468695, -35.93263169])],
 4: [0,
  Quaternion(0.8158529759570551, 0.3346063850660154, -0.2804423532466054, 0.3791761796323402),
  array([ 18.31905867, -16.19695867, -51.04242676])],
 5: [44543.97250352548,
  Quaternion(0.7868945955540179, 0.6111503150520987, 0.0815351183695834, 0.025381339051697028),
  array([-17.2440

In [27]:
model.run_remaining()

MSMS running for poses/out51.pdb
MSMS running for poses/out52.pdb
MSMS running for poses/out53.pdb
MSMS running for poses/out55.pdb
MSMS running for poses/out54.pdb
MSMS running for poses/out56.pdb
MSMS running for MSMS running forposes/out57.pdb 
poses/out58.pdb
MSMS running for poses/out59.pdb
MSMS running for poses/out60.pdb
MSMS finished with poses/out59.pdb
MSMS finished with poses/out57.pdb
MSMS running for poses/out59.pdb
MSMS finished with poses/out54.pdb
MSMS running for poses/out57.pdb
MSMS running for poses/out54.pdb
MSMS finished with poses/out58.pdb
MSMS finished with poses/out51.pdb
MSMS finished with poses/out60.pdb
MSMS finished with poses/out56.pdb
MSMS finished with MSMS finished withposes/out55.pdb 
poses/out53.pdb
MSMS running for poses/out51.pdb
MSMS running for poses/out58.pdb
MSMS running for poses/out60.pdb
MSMS running for poses/out56.pdb
MSMS finished with poses/out52.pdb
MSMS running for poses/out55.pdb
MSMS running for poses/out53.pdb
MSMS running for poses/

In [23]:
model.memeplexes

array([[ 2., 13., 31., 33., 42.],
       [40., 11., 37., 36., 44.],
       [ 9., 46., 19.,  3., 39.],
       [23., 32., 15., 38.,  1.],
       [35., 18.,  5., 34., 48.],
       [ 4., 27., 16., 22., 12.],
       [49., 10., 43., 20., 28.],
       [29.,  8., 47.,  6., 14.],
       [26., 24., 17.,  0., 25.],
       [ 7., 45., 41., 30., 21.]])

In [28]:
model.memeplexes

array([[ 2., 13., 31., 33., 42.],
       [40.,  8., 37., 36., 44.],
       [ 9., 11., 19.,  3., 39.],
       [23., 26., 15., 38.,  1.],
       [35., 46.,  5., 34., 48.],
       [ 4., 24., 16., 22., 12.],
       [27., 32., 43., 20., 28.],
       [49.,  7., 47.,  6., 14.],
       [10., 18., 17.,  0., 25.],
       [29., 45., 41., 30., 21.]])

In [26]:
model.structinfo[21]

[2.5286548556713836e+18,
 Quaternion(0.7601526864981566, -0.546707780925355, -0.05720738845053106, -0.34641854770202396),
 array([-22.2555501 ,  13.34884421,  11.5181412 ])]

In [21]:
??model.local_search

Signature: model.local_search()
Docstring: <no docstring>
Source:   
    def local_search(self):
        self.Frog_gb = self.structinfo[int(self.memeplexes[0][0])]
        
        with concurrent.futures.ProcessPoolExecutor() as executor:
            doargs = [im for im, _ in enumerate(self.memeplexes)]
            results = executor.map(self.local_search_one_memeplex, doargs)
File:      ~/Documents/SFLADock/src/sfla.py
Type:      method
